# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventos_db
spring.datasource.username=postgres
spring.datasource.password=kauan1701

# Dialeto do banco
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRIAÇÃO AUTOMÁTICA DAS TABELAS
spring.jpa.hibernate.ddl-auto=update

# Exibir os comandos SQL gerados no console (opcional, mas recomendado para aprendizado)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true